/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.io.ByteArrayOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;
import Funciones.*;
import coneccion.Conection;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSetMetaData;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Eduardo Orozco Cardenas <eduardo.orozco66@unach.mx>
 */
public class foraneo_admin extends javax.swing.JFrame {

    /**
     * Creates new form foraneo_admin7
     */
    public foraneo_admin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        jTable_bus.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                JTable table = new JTable();
                Point point = evt.getPoint();
                int row = table.rowAtPoint(point);
                int fila_point = jTable_bus.rowAtPoint(evt.getPoint());
                int columna_point = 0;
                if (evt.getClickCount() == 1) {
                    txt_id.setText(jTable_bus.getValueAt(jTable_bus.getSelectedRow(), 0).toString());
                    txt_nombre.setText(jTable_bus.getValueAt(jTable_bus.getSelectedRow(), 1).toString());
                    txt_app.setText(jTable_bus.getValueAt(jTable_bus.getSelectedRow(), 2).toString());
                    txt_apm.setText(jTable_bus.getValueAt(jTable_bus.getSelectedRow(), 3).toString());
                    txt_facu.setText(jTable_bus.getValueAt(jTable_bus.getSelectedRow(), 4).toString());
                }
            }
        });
    }

    Connection c;

    fondo_panel fondo = new fondo_panel();

    class fondo_panel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon("src/main/java/Iconos/tablas1.png").getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    ImageIcon iconobtn1 = new ImageIcon("src/main/java/Iconos/editar-codigo.png");
    ImageIcon iconobtn2 = new ImageIcon("src/main/java/Iconos/disquete.png");
    ImageIcon iconobtn3 = new ImageIcon("src/main/java/Iconos/basura.png");
    ImageIcon iconobtn4 = new ImageIcon("src/main/java/Iconos/lupa.png");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondo_panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_bus = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtAppat = new javax.swing.JTextField();
        txtApmat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        LabelNombre1 = new javax.swing.JLabel();
        txt_facu = new javax.swing.JTextField();
        Label_facu = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        Label_apm = new javax.swing.JLabel();
        txt_apm = new javax.swing.JTextField();
        txt_app = new javax.swing.JTextField();
        LabelID = new javax.swing.JLabel();
        Label_App = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_bus = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable_bus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_bus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido Paterno", "Apellido Materno", "Facultad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_bus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_bus.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_bus);
        if (jTable_bus.getColumnModel().getColumnCount() > 0) {
            jTable_bus.getColumnModel().getColumn(0).setResizable(false);
            jTable_bus.getColumnModel().getColumn(1).setResizable(false);
            jTable_bus.getColumnModel().getColumn(2).setResizable(false);
            jTable_bus.getColumnModel().getColumn(3).setResizable(false);
            jTable_bus.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        jLabel1.setText("Apellido Paterno :");

        txtAppat.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 16)); // NOI18N
        txtAppat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppatActionPerformed(evt);
            }
        });

        txtApmat.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 16)); // NOI18N
        txtApmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApmatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        jLabel2.setText("Apellido Materno :");

        btn_buscar1.setBackground(new java.awt.Color(29, 53, 100));
        btn_buscar1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        btn_buscar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar1.setIcon(iconobtn4);
        btn_buscar1.setText("Buscar");
        btn_buscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(29, 53, 100));
        jButton1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver todos");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LabelNombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNombre1.setText("Nombre :");

        txt_facu.setEditable(false);
        txt_facu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_facu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_facuActionPerformed(evt);
            }
        });

        Label_facu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_facu.setText("Facultad :");

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        Label_apm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_apm.setText("Apellido M :");

        txt_apm.setEditable(false);
        txt_apm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_app.setEditable(false);
        txt_app.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LabelID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelID.setText("ID del Alumno :");

        Label_App.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_App.setText("Apellido P :");

        txt_nombre.setEditable(false);
        txt_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(29, 53, 100));
        jButton2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        jButton2.setIcon(iconobtn1);
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(29, 53, 100));
        jButton3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        jButton3.setIcon(iconobtn3);
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(29, 53, 100));
        jButton4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        jButton4.setIcon(iconobtn2);
        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAppat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApmat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_facu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_facu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_apm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_apm))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_App)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_app))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelNombre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAppat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtApmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelID)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombre1)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_App)
                            .addComponent(txt_app, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_apm)
                            .addComponent(txt_apm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_facu)
                            .addComponent(txt_facu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_facuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_facuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_facuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel modelado = new DefaultTableModel();
            jTable_bus.setModel(modelado);

            //Agregar tres variables
            PreparedStatement ps;
            ResultSet rs;
            //Connection con= getConection();
            c = new Conection().conectar_foraneo();
            String sql = "SELECT * FROM foraneo order by id_foraneo ASC;";
            ps = c.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMetaD = rs.getMetaData();
            int cant_columnas = rsMetaD.getColumnCount();

            modelado.addColumn("id");
            modelado.addColumn("nombre");
            modelado.addColumn("apellido paterno");
            modelado.addColumn("apellido materno");
            modelado.addColumn("facultad");

            while (rs.next()) {
                Object[] filas = new Object[cant_columnas];

                for (int i = 0; i < cant_columnas; i++) {
                    filas[i] = rs.getObject(i + 1);

                }
                modelado.addRow(filas);
            }

        } catch (Exception e) {
            System.out.println(e);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar1ActionPerformed
        if (!txtAppat.getText().equals("") || !txtApmat.getText().equals("")) {
            try {
                DefaultTableModel modelado = new DefaultTableModel();
                jTable_bus.setModel(modelado);

                //Agregar tres variables
                PreparedStatement ps;
                ResultSet rs;
                //Connection con= getConection();
                c = new Conection().conectar_foraneo();
                String sql = "SELECT * FROM foraneo WHERE ap_pat ILIKE '%" + txtAppat.getText() + "' AND ap_mat ILIKE'%" + txtApmat.getText() + "' order by id_foraneo ASC;";
                ps = c.prepareStatement(sql);
                rs = ps.executeQuery();

                ResultSetMetaData rsMetaD = rs.getMetaData();
                int cant_columnas = rsMetaD.getColumnCount();

                modelado.addColumn("id");
                modelado.addColumn("nombre");
                modelado.addColumn("apellido paterno");
                modelado.addColumn("apellido materno");
                modelado.addColumn("facultad");

                while (rs.next()) {
                    Object[] filas = new Object[cant_columnas];

                    for (int i = 0; i < cant_columnas; i++) {
                        filas[i] = rs.getObject(i + 1);

                    }
                    modelado.addRow(filas);
                }

            } catch (Exception e) {
                System.out.println(e);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese ambos apellidos");
        }
    }//GEN-LAST:event_btn_buscar1ActionPerformed

    private void txtApmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApmatActionPerformed

    private void txtAppatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.txt_nombre.setEditable(true);
        this.txt_app.setEditable(true);
        this.txt_apm.setEditable(true);
        this.txt_facu.setEditable(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foraneo_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foraneo_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foraneo_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foraneo_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foraneo_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelNombre1;
    private javax.swing.JLabel Label_App;
    private javax.swing.JLabel Label_apm;
    private javax.swing.JLabel Label_facu;
    private javax.swing.JButton btn_buscar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_bus;
    private javax.swing.JTextField txtApmat;
    private javax.swing.JTextField txtAppat;
    private javax.swing.JTextField txt_apm;
    private javax.swing.JTextField txt_app;
    private javax.swing.JTextField txt_facu;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
