/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.io.ByteArrayOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;
import Funciones.*;
import coneccion.Conection;
import java.sql.ResultSetMetaData;
import java.sql.PreparedStatement;
import java.sql.*;
import static java.sql.JDBCType.NULL;

/**
 *
 * @author Jose Eduardo Orozco Cardenas <eduardo.orozco66@unach.mx>
 */
public class foraneo extends javax.swing.JFrame {

    /**
     * Creates new form foraneo
     */
    public foraneo() {
        initComponents();
        add_facultades();
        lblImagen.setBackground(Color.white);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    Guardar in = new Guardar();
    Connection c;

    fondo_panel fondo = new fondo_panel();

    class fondo_panel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon("src/main/java/Iconos/formulario_foraneo.png").getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    public void add_facultades() {
        ComboBoxFacultades.removeAllItems();
        ComboBoxFacultades.addItem("Seleccione");
        ComboBoxFacultades.addItem("Administracion");
        ComboBoxFacultades.addItem("Medicina Humana");
        ComboBoxFacultades.addItem("Quimica");
        ComboBoxFacultades.addItem("Pedagogia");
        ComboBoxFacultades.addItem("Derecho");
        ComboBoxFacultades.addItem("Lenguas");
        ComboBoxFacultades.addItem("Costeros");
        ComboBoxFacultades.addItem("Agronomia");
        ComboBoxFacultades.addItem("Humanidades");
        ComboBoxFacultades.addItem("Biociencias");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondo_panel();
        TXTnombre = new javax.swing.JTextField();
        txtAppat = new javax.swing.JTextField();
        txtApmat = new javax.swing.JTextField();
        ComboBoxFacultades = new javax.swing.JComboBox<>();
        lblImagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTnombre.setBackground(null);
        TXTnombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TXTnombre.setForeground(new java.awt.Color(0, 0, 0));
        TXTnombre.setBorder(null);
        TXTnombre.setCaretColor(new java.awt.Color(0, 0, 0));
        TXTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnombreActionPerformed(evt);
            }
        });

        txtAppat.setBackground(null);
        txtAppat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAppat.setForeground(new java.awt.Color(0, 0, 0));
        txtAppat.setBorder(null);
        txtAppat.setCaretColor(new java.awt.Color(0, 0, 0));
        txtAppat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAppat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppatActionPerformed(evt);
            }
        });

        txtApmat.setBackground(null);
        txtApmat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtApmat.setForeground(new java.awt.Color(0, 0, 0));
        txtApmat.setBorder(null);
        txtApmat.setCaretColor(new java.awt.Color(0, 0, 0));
        txtApmat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtApmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApmatActionPerformed(evt);
            }
        });

        ComboBoxFacultades.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        ComboBoxFacultades.setMaximumRowCount(5);
        ComboBoxFacultades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxFacultades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFacultadesActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(29, 53, 100));
        jButton1.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar y Generar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(ComboBoxFacultades, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtAppat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(txtApmat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)))
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(TXTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAppat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApmat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ComboBoxFacultades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnombreActionPerformed

    private void txtAppatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppatActionPerformed

    private void txtApmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApmatActionPerformed

    private void ComboBoxFacultadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFacultadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxFacultadesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (TXTnombre.getText().equals("") || txtAppat.getText().equals("") || ComboBoxFacultades.getSelectedItem().equals("Seleccione") || txtApmat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        } else {
            int pRes;
            String nombre_foraneo = TXTnombre.getText();
            String ap_pat = txtAppat.getText();
            String ap_mat = txtApmat.getText();
            String facultad = (String) ComboBoxFacultades.getSelectedItem();
            c = new Conection().conectar_foraneo();
            PreparedStatement ps;
            ResultSet rs;
            try {

                String sql_pro = "call guardar_foraneo('" + nombre_foraneo + "','" + ap_pat + "','" + ap_mat + "','" + facultad + "'," + NULL + ");";
                ps = c.prepareStatement(sql_pro);
                rs = ps.executeQuery();
                rs.next();
                pRes = rs.getInt("pRes");
                if (pRes == 1) {
                    JOptionPane.showMessageDialog(null, "Alumno(a) guardado(a) exitosamente", "exito", JOptionPane.INFORMATION_MESSAGE);
                    String sql = "SELECT id_foraneo FROM foraneo ORDER BY id_foraneo DESC LIMIT 1;";
                    ps = c.prepareStatement(sql);
                    rs = ps.executeQuery();
                    int id_foraneo = 0;
                    if (rs.next()) {
                        id_foraneo = rs.getInt("id_foraneo");
                    }
                    String texto_qr = (nombre_foraneo.substring(0, 1) + ap_pat.substring(0, 1) + ap_mat.substring(0, 1) + facultad.substring(0, 1) +  "FDN" + id_foraneo);
                    System.out.println(id_foraneo);
                    java.sql.Statement st = c.createStatement();
                    String sql_2 = "UPDATE FORANEO SET CODIGO='" + texto_qr + "'WHERE id_foraneo=" + id_foraneo + ";";
                    st.executeUpdate(sql_2);
                    ByteArrayOutputStream out = QRCode.from(texto_qr).to(ImageType.PNG).withSize(205, 205).stream();
                    ImageIcon imageIcon = new ImageIcon(out.toByteArray());
                    this.lblImagen.setIcon(imageIcon);
                } else if (pRes == 2) {
                    
                    JOptionPane.showMessageDialog(null, "El alumno(a) ya cuenta con un registro. Acuda con el administrador", "ya se tiene registro.", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foraneo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foraneo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foraneo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foraneo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foraneo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxFacultades;
    private javax.swing.JTextField TXTnombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtApmat;
    private javax.swing.JTextField txtAppat;
    // End of variables declaration//GEN-END:variables
}
