/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Emili
 */
public class Gestion extends javax.swing.JFrame {

    /**
     * Creates new form Gestion
     */
    public Gestion() {
        initComponents();
        setResizable(false); 
        setLocationRelativeTo(null);
        
        //IMPORTAR EL PANEL
        //inicio_gestion  = new inicio_gestion();
        ig.setSize (800,500);
        ig.setLocation (0,0);
        
        contenedor.removeAll();
        contenedor.add (ig, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();        
    }
    
    inicio_gestion ig = new inicio_gestion(); //importar panel inicio gestion
    
    fondo_panel fondo = new fondo_panel();
    class fondo_panel extends JPanel
    {
        private Image imagen;
        @Override
        public void paint(Graphics g)
        {
           imagen = new ImageIcon("src/main/java/Iconos/Gestion1.png").getImage();
           g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
           setOpaque(false);
           super.paint(g);
        }        
    }
    //iconos
    ImageIcon ichorarios = new ImageIcon("src/main/java/Iconos/reloj1.png");
    ImageIcon icalumno = new ImageIcon("src/main/java/Iconos/Gestion2.png");
    ImageIcon prueba = new ImageIcon("src/main/java/Iconos/gestion-de-equipos.png");
    ImageIcon inicio = new ImageIcon("src/main/java/Iconos/hogar.png");
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new fondo_panel();
        btn_ctrlhr1 = new javax.swing.JButton();
        btn_ctrlalum1 = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(850, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ctrlhr1.setIcon(ichorarios);
        btn_ctrlhr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ctrlhr1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ctrlhr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 49, 46));

        btn_ctrlalum1.setIcon(icalumno);
        btn_ctrlalum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ctrlalum1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ctrlalum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 49, 45));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel3.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 800, 500));

        jButton1.setIcon(inicio);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 42));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ctrlalum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ctrlalum1ActionPerformed
        // TODO add your handling code here:
        Gestion_usuarios gu = new Gestion_usuarios();
        gu.setSize (800,500);
        gu.setLocation (0,0);
        
        contenedor.removeAll();;
        contenedor.add (gu, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btn_ctrlalum1ActionPerformed

    private void btn_ctrlhr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ctrlhr1ActionPerformed
        // TODO add your handling code here:
        Gestion_horarios gh = new Gestion_horarios();
        gh.setSize (800,500);
        gh.setLocation (0,0);

        contenedor.removeAll();;
        contenedor.add (gh, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btn_ctrlhr1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ig.setSize (800,500);
        ig.setLocation (0,0);
        
        contenedor.removeAll();;
        contenedor.add (ig, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ctrlalum1;
    private javax.swing.JButton btn_ctrlhr1;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
