/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Emili
 */
public class Lab_windows extends javax.swing.JFrame {

    /**
     * Creates new form Login_alumno
     */
    public Lab_windows() {
        initComponents(); 
        setResizable(false); 
        setLocationRelativeTo(null);
    }
    
    fondo_panel fondo = new fondo_panel();
    class fondo_panel extends JPanel
    {
        private Image imagen;
        @Override
        public void paint(Graphics g)
        {
           imagen = new ImageIcon("src/main/java/Iconos/Pantalla_inicio_(1).png").getImage();
           g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
           setOpaque(false);
           super.paint(g);
        }
        
    }
    
    login_admin lgadmin = new login_admin();
    Escaner_alumno escaum = new Escaner_alumno();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new fondo_panel();
        btn_escanerforaneo = new javax.swing.JButton();
        btn_alumno = new javax.swing.JButton();
        btn_foraneo1 = new javax.swing.JButton();
        login_admin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_escanerforaneo.setBackground(new java.awt.Color(29, 53, 100));
        btn_escanerforaneo.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        btn_escanerforaneo.setForeground(new java.awt.Color(255, 255, 255));
        btn_escanerforaneo.setText("ESCANEA AQUÍ");
        btn_escanerforaneo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_escanerforaneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_escanerforaneoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_escanerforaneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 330, 50));

        btn_alumno.setBackground(new java.awt.Color(255, 255, 255));
        btn_alumno.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        btn_alumno.setForeground(new java.awt.Color(0, 0, 0));
        btn_alumno.setText("ESCANEA TU CÓDIGO");
        btn_alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alumnoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 330, 50));

        btn_foraneo1.setBackground(new java.awt.Color(29, 53, 100));
        btn_foraneo1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        btn_foraneo1.setForeground(new java.awt.Color(255, 255, 255));
        btn_foraneo1.setText("RELLENA TU FORMULARIO");
        btn_foraneo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_foraneo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_foraneo1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_foraneo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 330, 50));

        login_admin.setText("ADMIN");
        login_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_adminActionPerformed(evt);
            }
        });
        jPanel2.add(login_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_escanerforaneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escanerforaneoActionPerformed
        // TODO add your handling code here: ACCION FORANEO
        
    }//GEN-LAST:event_btn_escanerforaneoActionPerformed

    private void btn_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alumnoActionPerformed
        // TODO add your handling code here: ACCION ALUMNO
        if(evt.getSource() == btn_alumno)
        {
            btn_alumno.setEnabled(false);
            btn_foraneo1.setEnabled(false);
            btn_escanerforaneo.setEnabled(false); 
            login_admin.setEnabled(false);
                       
            escaum.setVisible(true);            
            
            escaum.addWindowListener(new WindowAdapter(){
               @Override
               public void windowClosing(WindowEvent we){
                    btn_alumno.setEnabled(true);
                    btn_foraneo1.setEnabled(true);
                    btn_escanerforaneo.setEnabled(true);
                    login_admin.setEnabled(true);                 
               }
               public void windowClosed(WindowEvent we)
               {
                    btn_alumno.setEnabled(true);
                    btn_foraneo1.setEnabled(true);
                    btn_escanerforaneo.setEnabled(true);
                    login_admin.setEnabled(true);                    
               }
           });
        }       
    }//GEN-LAST:event_btn_alumnoActionPerformed

    private void btn_foraneo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_foraneo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_foraneo1ActionPerformed

    private void login_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_adminActionPerformed
        // TODO add your handling code here:
        lgadmin.setVisible(true);
        this.dispose();
        lgadmin.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent we){
                setVisible(true);
            }           
        });
    }//GEN-LAST:event_login_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab_windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab_windows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alumno;
    private javax.swing.JButton btn_escanerforaneo;
    private javax.swing.JButton btn_foraneo1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_admin;
    // End of variables declaration//GEN-END:variables
}
